seurl = "/"                   # The base URL of your Hugo site
title = "caleb cranford"             # The title of your Hugo site
author = "cc"           # The author name
googleAnalytics = ""            # Your Google Analytics tracking ID
enableRobotsTXT = true
defaultContentLanguage = "en"
language = "en-US"
paginate = 7                    # The numbers of posts per page
theme = "hermit"               # Your Hugo theme

[params]
  customCSS = ["css/bgcanvas.css", ]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"